apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-httpd-app
  lables:
    app: my-httpd-app
spec:
  replicas: 2
  selector:
    matchLables:
      app: my-httpd-app
  template:
    metadata:
      lables:
        app: my-httpd-app
    spec:
      containers:
       - name: my-httpd-app
         image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/my-httpd-app:latest
         port:
          - containerPort: 80