apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-httpd-app
  labels:
    app: my-httpd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-httpd-app
  template:
    metadata:
      labels:
        app: my-httpd-app
    spec:
      containers:
        - name: my-httpd-app
          image: 420518854293.dkr.ecr.ap-south-1.amazonaws.com/my-httpd-app:latest
          ports:
            - containerPort: 80
