apiVersion: v1 
kind: Service
metadata:
  name: httpd-service
spec:
  type: LoadBalancer
  selector:
    lables:
      app: my-httpd-app
  ports:
    - protocol: TCP
      port: 80
      targetport: 80